sudo: required

language: java
jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: searchpe
    token:
      secure: $SONAR_TOKEN

services:
  - docker

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -P !build-extras -B
  - mvn jacoco:report coveralls:report -Dcoveralls.token=$COVERALLS_TOKEN
  - sonar-scanner

cache:
  directories:
  - "~/.m2/repository"

after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"